# Generated by Django 4.2 on 2026-02-17 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modifier',
            name='modifier_type',
            field=models.CharField(choices=[('size', 'Size'), ('sugar', 'Sugar Level'), ('ice', 'Ice Level'), ('temperature', 'Temperature')], max_length=20),
        ),
    ]
